//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XslTransformer.Core.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XslTransformer.Core.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string AddedParameterNamePrefix {
            get {
                return ResourceManager.GetString("AddedParameterNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string AddedParameterValuePrefix {
            get {
                return ResourceManager.GetString("AddedParameterValuePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Parameter ähnelt.
        /// </summary>
        public static string AddParameter {
            get {
                return ResourceManager.GetString("AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add XSLT Stylesheet(s) ähnelt.
        /// </summary>
        public static string AddXslt {
            get {
                return ResourceManager.GetString("AddXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose XSLT File(s) ähnelt.
        /// </summary>
        public static string AddXsltDialogTitle {
            get {
                return ResourceManager.GetString("AddXsltDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow XML attributes (xml:*) without Schema definition ähnelt.
        /// </summary>
        public static string AllowXmlAttributes {
            get {
                return ResourceManager.GetString("AllowXmlAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check characters and names ähnelt.
        /// </summary>
        public static string CheckCharacters {
            get {
                return ResourceManager.GetString("CheckCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose XML Input File ähnelt.
        /// </summary>
        public static string ChooseXmlInputFileDialogTitle {
            get {
                return ResourceManager.GetString("ChooseXmlInputFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DTD Processing ähnelt.
        /// </summary>
        public static string DtdProcessing {
            get {
                return ResourceManager.GetString("DtdProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable XSLT document() function ähnelt.
        /// </summary>
        public static string EnableDocumentFunction {
            get {
                return ResourceManager.GetString("EnableDocumentFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable embedded scripts ähnelt.
        /// </summary>
        public static string EnableScript {
            get {
                return ResourceManager.GetString("EnableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}› could not be opened. ähnelt.
        /// </summary>
        public static string FileNotFoundMsgText {
            get {
                return ResourceManager.GetString("FileNotFoundMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not Found ähnelt.
        /// </summary>
        public static string FileNotFoundMsgTitle {
            get {
                return ResourceManager.GetString("FileNotFoundMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File: ‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string OutputFileErrorMsgText {
            get {
                return ResourceManager.GetString("OutputFileErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Writing Result File ähnelt.
        /// </summary>
        public static string OutputFileErrorMsgTitle {
            get {
                return ResourceManager.GetString("OutputFileErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Name ähnelt.
        /// </summary>
        public static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameter name must be unique. ähnelt.
        /// </summary>
        public static string ParameterNameDoubleError {
            get {
                return ResourceManager.GetString("ParameterNameDoubleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a parameter name. ähnelt.
        /// </summary>
        public static string ParameterNameMissingError {
            get {
                return ResourceManager.GetString("ParameterNameMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Type ähnelt.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter Vale ähnelt.
        /// </summary>
        public static string ParameterValue {
            get {
                return ResourceManager.GetString("ParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check xs:ID, xs:IDREF, xs:key, xs:keyref, xs:unique ähnelt.
        /// </summary>
        public static string ProcessIdentityConstraints {
            get {
                return ResourceManager.GetString("ProcessIdentityConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process inline schemas ähnelt.
        /// </summary>
        public static string ProcessInlineSchema {
            get {
                return ResourceManager.GetString("ProcessInlineSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process schema location hints (xsi:schemaLocation,
        ///xsi:noNamespaceSchemaLocation) ähnelt.
        /// </summary>
        public static string ProcessSchemaLocation {
            get {
                return ResourceManager.GetString("ProcessSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Parameter ähnelt.
        /// </summary>
        public static string RemoveParameter {
            get {
                return ResourceManager.GetString("RemoveParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove XSLT stylesheet ähnelt.
        /// </summary>
        public static string RemoveXslt {
            get {
                return ResourceManager.GetString("RemoveXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report schema validation warnings ähnelt.
        /// </summary>
        public static string ReportValidationWarnings {
            get {
                return ResourceManager.GetString("ReportValidationWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Result File ähnelt.
        /// </summary>
        public static string SaveResultFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveResultFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schema Validation ähnelt.
        /// </summary>
        public static string SchemaValidation {
            get {
                return ResourceManager.GetString("SchemaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last processed XSLT stylesheet:
        ///‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string TransformationResultErrorMsgText {
            get {
                return ResourceManager.GetString("TransformationResultErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error While Further Processing a Transformation Result ähnelt.
        /// </summary>
        public static string TransformationResultErrorMsgTitle {
            get {
                return ResourceManager.GetString("TransformationResultErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The transformation was successfully completed. ähnelt.
        /// </summary>
        public static string TransformationSuccessMsgText {
            get {
                return ResourceManager.GetString("TransformationSuccessMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transformation Completed ähnelt.
        /// </summary>
        public static string TransformationSuccessMsgTitle {
            get {
                return ResourceManager.GetString("TransformationSuccessMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transform XML and Save Result ähnelt.
        /// </summary>
        public static string TransformXmlAndSaveResult {
            get {
                return ResourceManager.GetString("TransformXmlAndSaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation ähnelt.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation Type ähnelt.
        /// </summary>
        public static string ValidationType {
            get {
                return ResourceManager.GetString("ValidationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write UTF-8 BOM (Byte Order Mark) ähnelt.
        /// </summary>
        public static string WriteUtf8Bom {
            get {
                return ResourceManager.GetString("WriteUtf8Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Input File ähnelt.
        /// </summary>
        public static string XmlInputFile {
            get {
                return ResourceManager.GetString("XmlInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XmlInputFileErrorMsgText {
            get {
                return ResourceManager.GetString("XmlInputFileErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading XML Input File ähnelt.
        /// </summary>
        public static string XmlInputFileErrorMsgTitle {
            get {
                return ResourceManager.GetString("XmlInputFileErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XmlInputFileValidationErrorMsgText {
            get {
                return ResourceManager.GetString("XmlInputFileValidationErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation Error while Loading XML Input File ähnelt.
        /// </summary>
        public static string XmlInputFileValidationErrorMsgTitle {
            get {
                return ResourceManager.GetString("XmlInputFileValidationErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Parser ähnelt.
        /// </summary>
        public static string XmlParser {
            get {
                return ResourceManager.GetString("XmlParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, apply ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogButtonApply {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogButtonDontApply {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogButtonDontApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apply ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogHeaderApply {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogHeaderApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die href Attribute ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogHeaderHref {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogHeaderHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die media Attribute ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogHeaderMedia {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogHeaderMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shall the selected stylesheets be applied in XslTransformer? Existing stylesheets in the list will be replaced. ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogQuestion {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one xml-stylesheet declaration was found in the XML input file. ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogText {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Stylesheet Declaration(s) found ähnelt.
        /// </summary>
        public static string XmlStylesheetDialogTitle {
            get {
                return ResourceManager.GetString("XmlStylesheetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation Error ähnelt.
        /// </summary>
        public static string XmlValidationErrorMsgTitle {
            get {
                return ResourceManager.GetString("XmlValidationErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description:
        ///{0} ähnelt.
        /// </summary>
        public static string XmlValidationMsgText {
            get {
                return ResourceManager.GetString("XmlValidationMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation Warning ähnelt.
        /// </summary>
        public static string XmlValidationWarningMsgTitle {
            get {
                return ResourceManager.GetString("XmlValidationWarningMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XsltErrorMsgText {
            get {
                return ResourceManager.GetString("XsltErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Loading XSLT File ähnelt.
        /// </summary>
        public static string XsltErrorMsgTitle {
            get {
                return ResourceManager.GetString("XsltErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transformation Parameters ähnelt.
        /// </summary>
        public static string XsltParameters {
            get {
                return ResourceManager.GetString("XsltParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processed XSLT stylesheet:
        ///‹{0}›
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XslTransformationErrorMsgText {
            get {
                return ResourceManager.GetString("XslTransformationErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error During XSL Transformation ähnelt.
        /// </summary>
        public static string XslTransformationErrorMsgTitle {
            get {
                return ResourceManager.GetString("XslTransformationErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XSL Transformation(s) ähnelt.
        /// </summary>
        public static string XslTransformations {
            get {
                return ResourceManager.GetString("XslTransformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XslTransformer Settings ähnelt.
        /// </summary>
        public static string XslTransformerSettings {
            get {
                return ResourceManager.GetString("XslTransformerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}› is not well-formed:
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XsltXmlErrorMsgText {
            get {
                return ResourceManager.GetString("XsltXmlErrorMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ‹{0}› contains Errors:
        ///
        ///Description:
        ///{1} ähnelt.
        /// </summary>
        public static string XsltXsltErrorMsgText {
            get {
                return ResourceManager.GetString("XsltXsltErrorMsgText", resourceCulture);
            }
        }
    }
}
